// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.3
// source: ts_bot_service.proto

package grpc_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PairingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID string `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	ChipID string `protobuf:"bytes,2,opt,name=chipID,proto3" json:"chipID,omitempty"`
}

func (x *PairingRequest) Reset() {
	*x = PairingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ts_bot_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PairingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairingRequest) ProtoMessage() {}

func (x *PairingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ts_bot_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairingRequest.ProtoReflect.Descriptor instead.
func (*PairingRequest) Descriptor() ([]byte, []int) {
	return file_ts_bot_service_proto_rawDescGZIP(), []int{0}
}

func (x *PairingRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *PairingRequest) GetChipID() string {
	if x != nil {
		return x.ChipID
	}
	return ""
}

type PairedSensorsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID string `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
}

func (x *PairedSensorsRequest) Reset() {
	*x = PairedSensorsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ts_bot_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PairedSensorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairedSensorsRequest) ProtoMessage() {}

func (x *PairedSensorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ts_bot_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairedSensorsRequest.ProtoReflect.Descriptor instead.
func (*PairedSensorsRequest) Descriptor() ([]byte, []int) {
	return file_ts_bot_service_proto_rawDescGZIP(), []int{1}
}

func (x *PairedSensorsRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type PairedSensorsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChipID []string `protobuf:"bytes,1,rep,name=chipID,proto3" json:"chipID,omitempty"`
}

func (x *PairedSensorsResponse) Reset() {
	*x = PairedSensorsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ts_bot_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PairedSensorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairedSensorsResponse) ProtoMessage() {}

func (x *PairedSensorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ts_bot_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairedSensorsResponse.ProtoReflect.Descriptor instead.
func (*PairedSensorsResponse) Descriptor() ([]byte, []int) {
	return file_ts_bot_service_proto_rawDescGZIP(), []int{2}
}

func (x *PairedSensorsResponse) GetChipID() []string {
	if x != nil {
		return x.ChipID
	}
	return nil
}

type LatestMeasurementSearch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChipID string `protobuf:"bytes,1,opt,name=chipID,proto3" json:"chipID,omitempty"`
}

func (x *LatestMeasurementSearch) Reset() {
	*x = LatestMeasurementSearch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ts_bot_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LatestMeasurementSearch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LatestMeasurementSearch) ProtoMessage() {}

func (x *LatestMeasurementSearch) ProtoReflect() protoreflect.Message {
	mi := &file_ts_bot_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LatestMeasurementSearch.ProtoReflect.Descriptor instead.
func (*LatestMeasurementSearch) Descriptor() ([]byte, []int) {
	return file_ts_bot_service_proto_rawDescGZIP(), []int{3}
}

func (x *LatestMeasurementSearch) GetChipID() string {
	if x != nil {
		return x.ChipID
	}
	return ""
}

type Measurement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SoilMoisture float32                `protobuf:"fixed32,3,opt,name=soilMoisture,proto3" json:"soilMoisture,omitempty"`
	Temperature  float32                `protobuf:"fixed32,4,opt,name=temperature,proto3" json:"temperature,omitempty"`
	Humidity     float32                `protobuf:"fixed32,5,opt,name=humidity,proto3" json:"humidity,omitempty"`
	Pressure     float32                `protobuf:"fixed32,6,opt,name=pressure,proto3" json:"pressure,omitempty"`
	Altitude     float32                `protobuf:"fixed32,7,opt,name=altitude,proto3" json:"altitude,omitempty"`
}

func (x *Measurement) Reset() {
	*x = Measurement{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ts_bot_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Measurement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Measurement) ProtoMessage() {}

func (x *Measurement) ProtoReflect() protoreflect.Message {
	mi := &file_ts_bot_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Measurement.ProtoReflect.Descriptor instead.
func (*Measurement) Descriptor() ([]byte, []int) {
	return file_ts_bot_service_proto_rawDescGZIP(), []int{4}
}

func (x *Measurement) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Measurement) GetSoilMoisture() float32 {
	if x != nil {
		return x.SoilMoisture
	}
	return 0
}

func (x *Measurement) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *Measurement) GetHumidity() float32 {
	if x != nil {
		return x.Humidity
	}
	return 0
}

func (x *Measurement) GetPressure() float32 {
	if x != nil {
		return x.Pressure
	}
	return 0
}

func (x *Measurement) GetAltitude() float32 {
	if x != nil {
		return x.Altitude
	}
	return 0
}

var File_ts_bot_service_proto protoreflect.FileDescriptor

var file_ts_bot_service_proto_rawDesc = []byte{
	0x0a, 0x14, 0x74, 0x73, 0x5f, 0x62, 0x6f, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x70, 0x62, 0x1a,
	0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x40, 0x0a,
	0x0e, 0x50, 0x61, 0x69, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x68, 0x69, 0x70, 0x49,
	0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x68, 0x69, 0x70, 0x49, 0x44, 0x22,
	0x2e, 0x0a, 0x14, 0x50, 0x61, 0x69, 0x72, 0x65, 0x64, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x22,
	0x2f, 0x0a, 0x15, 0x50, 0x61, 0x69, 0x72, 0x65, 0x64, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x68, 0x69, 0x70,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x63, 0x68, 0x69, 0x70, 0x49, 0x44,
	0x22, 0x31, 0x0a, 0x17, 0x4c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x4d, 0x65, 0x61, 0x73, 0x75, 0x72,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x63,
	0x68, 0x69, 0x70, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x68, 0x69,
	0x70, 0x49, 0x44, 0x22, 0xe1, 0x01, 0x0a, 0x0b, 0x4d, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x22, 0x0a,
	0x0c, 0x73, 0x6f, 0x69, 0x6c, 0x4d, 0x6f, 0x69, 0x73, 0x74, 0x75, 0x72, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x0c, 0x73, 0x6f, 0x69, 0x6c, 0x4d, 0x6f, 0x69, 0x73, 0x74, 0x75, 0x72,
	0x65, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x65, 0x6d, 0x70, 0x65, 0x72, 0x61, 0x74, 0x75, 0x72, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0b, 0x74, 0x65, 0x6d, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x75, 0x6d, 0x69, 0x64, 0x69, 0x74, 0x79, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x68, 0x75, 0x6d, 0x69, 0x64, 0x69, 0x74, 0x79, 0x12,
	0x1a, 0x0a, 0x08, 0x70, 0x72, 0x65, 0x73, 0x73, 0x75, 0x72, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x08, 0x70, 0x72, 0x65, 0x73, 0x73, 0x75, 0x72, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x61,
	0x6c, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x61,
	0x6c, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x32, 0xfb, 0x01, 0x0a, 0x14, 0x54, 0x65, 0x72, 0x72,
	0x61, 0x53, 0x65, 0x6e, 0x73, 0x65, 0x42, 0x6f, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x3f, 0x0a, 0x0a, 0x50, 0x61, 0x69, 0x72, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x12, 0x17,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x70, 0x62, 0x2e, 0x50, 0x61, 0x69, 0x72, 0x69, 0x6e, 0x67,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22,
	0x00, 0x12, 0x50, 0x0a, 0x0d, 0x50, 0x61, 0x69, 0x72, 0x65, 0x64, 0x53, 0x65, 0x6e, 0x73, 0x6f,
	0x72, 0x73, 0x12, 0x1d, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x70, 0x62, 0x2e, 0x50, 0x61, 0x69,
	0x72, 0x65, 0x64, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1e, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x70, 0x62, 0x2e, 0x50, 0x61, 0x69, 0x72,
	0x65, 0x64, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x50, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x74, 0x65, 0x73, 0x74,
	0x4d, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x20, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x5f, 0x70, 0x62, 0x2e, 0x4c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x4d, 0x65, 0x61, 0x73,
	0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x1a, 0x14, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x5f, 0x70, 0x62, 0x2e, 0x4d, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x22, 0x00, 0x42, 0x27, 0x5a, 0x25, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x50, 0x61, 0x6f, 0x6c, 0x6f, 0x45, 0x47, 0x2f, 0x74, 0x65, 0x72, 0x72,
	0x61, 0x73, 0x65, 0x6e, 0x73, 0x65, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ts_bot_service_proto_rawDescOnce sync.Once
	file_ts_bot_service_proto_rawDescData = file_ts_bot_service_proto_rawDesc
)

func file_ts_bot_service_proto_rawDescGZIP() []byte {
	file_ts_bot_service_proto_rawDescOnce.Do(func() {
		file_ts_bot_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_ts_bot_service_proto_rawDescData)
	})
	return file_ts_bot_service_proto_rawDescData
}

var file_ts_bot_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_ts_bot_service_proto_goTypes = []interface{}{
	(*PairingRequest)(nil),          // 0: grpc_pb.PairingRequest
	(*PairedSensorsRequest)(nil),    // 1: grpc_pb.PairedSensorsRequest
	(*PairedSensorsResponse)(nil),   // 2: grpc_pb.PairedSensorsResponse
	(*LatestMeasurementSearch)(nil), // 3: grpc_pb.LatestMeasurementSearch
	(*Measurement)(nil),             // 4: grpc_pb.Measurement
	(*timestamppb.Timestamp)(nil),   // 5: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),           // 6: google.protobuf.Empty
}
var file_ts_bot_service_proto_depIdxs = []int32{
	5, // 0: grpc_pb.Measurement.timestamp:type_name -> google.protobuf.Timestamp
	0, // 1: grpc_pb.TerraSenseBotService.PairSensor:input_type -> grpc_pb.PairingRequest
	1, // 2: grpc_pb.TerraSenseBotService.PairedSensors:input_type -> grpc_pb.PairedSensorsRequest
	3, // 3: grpc_pb.TerraSenseBotService.GetLatestMeasurement:input_type -> grpc_pb.LatestMeasurementSearch
	6, // 4: grpc_pb.TerraSenseBotService.PairSensor:output_type -> google.protobuf.Empty
	2, // 5: grpc_pb.TerraSenseBotService.PairedSensors:output_type -> grpc_pb.PairedSensorsResponse
	4, // 6: grpc_pb.TerraSenseBotService.GetLatestMeasurement:output_type -> grpc_pb.Measurement
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ts_bot_service_proto_init() }
func file_ts_bot_service_proto_init() {
	if File_ts_bot_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ts_bot_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PairingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ts_bot_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PairedSensorsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ts_bot_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PairedSensorsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ts_bot_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LatestMeasurementSearch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ts_bot_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Measurement); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ts_bot_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ts_bot_service_proto_goTypes,
		DependencyIndexes: file_ts_bot_service_proto_depIdxs,
		MessageInfos:      file_ts_bot_service_proto_msgTypes,
	}.Build()
	File_ts_bot_service_proto = out.File
	file_ts_bot_service_proto_rawDesc = nil
	file_ts_bot_service_proto_goTypes = nil
	file_ts_bot_service_proto_depIdxs = nil
}
