version: '3.8'

services:
  db:
    image: arm64v8/postgres:alpine
    env_file:
      - deploy.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  go-ingestor:
    build:
      context: .
      dockerfile: arm64-server.dockerfile
    env_file:
      - deploy.env
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  pgdata:
