name: rpi-deploy

on:
  push:
    branches: [deploy]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Run docker-compose
        run: cd be && docker compose -f arm64-docker-compose.yaml up --build --force-recreate -d
