name: rpi-deploy

on:
  push:
    branches: [deploy]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Create .env file
        uses: SpicyPizza/create-envfile@v2.0.3
        with:
          MQTT_HOST: ${{ vars.MQTT_HOST }}
          MQTT_PORT: ${{ vars.MQTT_PORT }}
          MQTT_CLIENTID: ${{ vars.MQTT_CLIENTID }}
          MQTT_USERNAME: ${{ vars.MQTT_USERNAME }}
          MQTT_PWD: ${{ secrets.MQTT_PWD }}
          POSTGRES_URL: ${{ vars.POSTGRES_URL }}
          POSTGRES_PORT: ${{ vars.POSTGRES_PORT }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

      - name: Run docker-compose
        run: cd be && docker compose -f arm64-docker-compose.yaml up --build --force-recreate -d
